# Generated by Django 6.0 on 2026-01-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('product_name', models.CharField(max_length=200)),
                ('product_details', models.CharField(max_length=200)),
                ('stock_status', models.CharField(max_length=20)),
                ('project_type', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=50)),
                ('total_area', models.CharField(max_length=50)),
                ('additional_notes', models.TextField(blank=True)),
                ('admin_reply', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
