# Generated by Django 6.0 on 2026-01-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('florra', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerToken',
        ),
    ]
