# Generated by Django 6.0 on 2026-01-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra', '0008_product_brand_name_product_category_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
