# Generated by Django 5.1.4 on 2026-05-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra', '0011_alter_favorite_product_alter_customertoken_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='product_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
