# Generated by Django 5.1.4 on 2026-05-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra', '0012_notification_product_id_notification_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('system', 'System'), ('promotion', 'Promotion'), ('alert', 'Alert'), ('announcement', 'Announcement')], max_length=20),
        ),
    ]
