# Generated by Django 5.1.4 on 2026-05-20 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra', '0013_remove_notification_product_id_and_more'),
        ('florra_admin', '0021_enquiry_admin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='florra_admin.product'),
        ),
    ]
