# Generated by Django 6.0 on 2026-01-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra_admin', '0002_admintoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('Ceramic', 'Ceramic'), ('Porcelain', 'Porcelain'), ('Vitrified', 'Vitrified'), ('Mosaic', 'Mosaic'), ('Natural Stone', 'Natural Stone'), ('Glass', 'Glass')], max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('finish', models.CharField(choices=[('Glossy', 'Glossy'), ('Matte', 'Matte'), ('Satin', 'Satin'), ('Rustic', 'Rustic')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
