# Generated by Django 6.0 on 2026-01-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra_admin', '0006_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='quotation_boxes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='quotation_delivery_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='quotation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='quotation_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
