# Generated by Django 6.0 on 2026-01-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra_admin', '0007_enquiry_customer_email_enquiry_quotation_boxes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='product_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='product_quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
