# Generated by Django 6.0 on 2026-01-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra_admin', '0008_enquiry_product_image_enquiry_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='project_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='room_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='total_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
