# Generated by Django 6.0 on 2026-01-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('florra_admin', '0009_enquiry_project_type_enquiry_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='total_area',
        ),
    ]
