# Generated by Django 6.0 on 2026-02-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra_admin', '0010_remove_enquiry_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tile_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Living', 'Living'), ('Bathroom', 'Bathroom'), ('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Wall', 'Wall'), ('Floor', 'Floor'), ('Ceramic', 'Ceramic'), ('Porcelain', 'Porcelain'), ('Vitrified', 'Vitrified'), ('Mosaic', 'Mosaic'), ('Natural Stone', 'Natural Stone'), ('Glass', 'Glass')], max_length=50),
        ),
    ]
