# Generated by Django 5.1.4 on 2026-05-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra_admin', '0012_alter_admintoken_id_alter_adminuser_id_alter_bill_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('system', 'System'), ('promotion', 'Promotion'), ('alert', 'Alert'), ('announcement', 'Announcement')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.CharField(default='Admin', max_length=100)),
            ],
        ),
    ]
