# Generated by Django 5.1.4 on 2026-05-11 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra_admin', '0013_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='product_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='tagged_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to='florra_admin.product'),
        ),
    ]
