# Generated by Django 5.1.4 on 2026-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra_admin', '0014_adminnotification_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminnotification',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='tagged_product',
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
