# Generated by Django 5.1.4 on 2026-05-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra_admin', '0015_remove_adminnotification_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Living', 'Living'), ('Bathroom', 'Bathroom'), ('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Wall', 'Wall'), ('Floor', 'Floor'), ('Parking', 'Parking'), ('Steps', 'Steps'), ('Roof', 'Roof'), ('Ceramic', 'Ceramic'), ('Porcelain', 'Porcelain'), ('Vitrified', 'Vitrified'), ('Mosaic', 'Mosaic'), ('Natural Stone', 'Natural Stone'), ('Glass', 'Glass')], max_length=50),
        ),
    ]
