# Generated by Django 5.1.4 on 2026-05-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra_admin', '0016_adminuser_role_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='allow_billing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='allow_reports',
            field=models.BooleanField(default=True),
        ),
    ]
