# Generated by Django 5.1.4 on 2026-05-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra_admin', '0017_adminuser_allow_billing_adminuser_allow_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='allow_billing',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='allow_reports',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='can_access_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='can_access_reports',
            field=models.BooleanField(default=False),
        ),
    ]
