# Generated by Django 5.1.4 on 2026-05-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florra_admin', '0020_adminuser_mobile_adminuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='admin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
